using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Windows.Forms;
using System.Xml.Serialization;

namespace WindowsFormsApplication2
{
    public static class MainSettings
    {
        public static CSIDInfo GetCSIDInfo()
        {
            CSIDInfo info = new CSIDInfo();
            try
            {
                try
                {
                    info.PublicKey = File.ReadAllText(Directory.GetCurrentDirectory() + "\\cert\\cert.pem");
                    info.PrivateKey = File.ReadAllText(Directory.GetCurrentDirectory() + "\\cert\\key.pem");
                    info.SecretKey = File.ReadAllText(Directory.GetCurrentDirectory() + "\\cert\\secret.txt");

                
                }
                catch
                {
                    //info.PublicKey = @"MIID9jCCA5ugAwIBAgITbwAAeCy9aKcLA99HrAABAAB4LDAKBggqhkjOPQQDAjBjMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNnb3YxFzAVBgoJkiaJk/IsZAEZFgdleHRnYXp0MRwwGgYDVQQDExNUU1pFSU5WT0lDRS1TdWJDQS0xMB4XDTIyMDQxOTIwNDkwOVoXDTI0MDQxODIwNDkwOVowWTELMAkGA1UEBhMCU0ExEzARBgNVBAoTCjMxMjM0NTY3ODkxDDAKBgNVBAsTA1RTVDEnMCUGA1UEAxMeVFNULS05NzA1NjAwNDAtMzEyMzQ1Njc4OTAwMDAzMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEYYMMoOaFYAhMO/steotfZyavr6p11SSlwsK9azmsLY7b1b+FLhqMArhB2dqHKboxqKNfvkKDePhpqjui5hcn0aOCAjkwggI1MIGaBgNVHREEgZIwgY+kgYwwgYkxOzA5BgNVBAQMMjEtVFNUfDItVFNUfDMtNDdmMTZjMjYtODA2Yi00ZTE1LWIyNjktN2E4MDM4ODRiZTljMR8wHQYKCZImiZPyLGQBAQwPMzEyMzQ1Njc4OTAwMDAzMQ0wCwYDVQQMDAQxMTAwMQwwCgYDVQQaDANUU1QxDDAKBgNVBA8MA1RTVDAdBgNVHQ4EFgQUO5ZiU7NakU3eejVa3I2S1B2sDwkwHwYDVR0jBBgwFoAUdmCM+wagrGdXNZ3PmqynK5k1tS8wTgYDVR0fBEcwRTBDoEGgP4Y9aHR0cDovL3RzdGNybC56YXRjYS5nb3Yuc2EvQ2VydEVucm9sbC9UU1pFSU5WT0lDRS1TdWJDQS0xLmNybDCBrQYIKwYBBQUHAQEEgaAwgZ0wbgYIKwYBBQUHMAGGYmh0dHA6Ly90c3RjcmwuemF0Y2EuZ292LnNhL0NlcnRFbnJvbGwvVFNaRWludm9pY2VTQ0ExLmV4dGdhenQuZ292LmxvY2FsX1RTWkVJTlZPSUNFLVN1YkNBLTEoMSkuY3J0MCsGCCsGAQUFBzABhh9odHRwOi8vdHN0Y3JsLnphdGNhLmdvdi5zYS9vY3NwMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwMwJwYJKwYBBAGCNxUKBBowGDAKBggrBgEFBQcDAjAKBggrBgEFBQcDAzAKBggqhkjOPQQDAgNJADBGAiEA7mHT6yg85jtQGWp3M7tPT7Jk2+zsvVHGs3bU5Z7YE68CIQD60ebQamYjYvdebnFjNfx4X4dop7LsEBFCNSsLY0IFaQ==";
                    //info.PrivateKey = @"MHQCAQEEIDyLDaWIn/1/g3PGLrwupV4nTiiLKM59UEqUch1vDfhpoAcGBSuBBAAKoUQDQgAEYYMMoOaFYAhMO/steotfZyavr6p11SSlwsK9azmsLY7b1b+FLhqMArhB2dqHKboxqKNfvkKDePhpqjui5hcn0Q==";
                    //info.SecretKey = @"";

                    info.PublicKey = @"MIIFBDCCBKugAwIBAgITeAAAW5gD14y6itV8AQABAABbmDAKBggqhkjOPQQDAjBiMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNnb3YxFzAVBgoJkiaJk/IsZAEZFgdleHRnYXp0MRswGQYDVQQDExJQRVpFSU5WT0lDRVNDQTQtQ0EwHhcNMjUwMTE2MTA1MjQ4WhcNMjcwMTE2MTEwMjQ4WjBuMQswCQYDVQQGEwJTQTEkMCIGA1UEChMbVGhhbGFhIE1hbGwgdHJhZGluZyBDb21wYW55MRAwDgYDVQQLEwdTSEFRRUVRMScwJQYDVQQDEx5ORVMtMjA1MDAxMjA5NS0zMDA1ODkyODQ5MDAwMDMwVjAQBgcqhkjOPQIBBgUrgQQACgNCAAQJ8rrhoPC42bV5grT+Ztzort5ciYGeg2nLhWNiz9BBbg3UQE+MsqISeC+URFFtw4JvlAqQvuOv+52s1GcvXXvTo4IDNTCCAzEwgZ8GA1UdEQSBlzCBlKSBkTCBjjE7MDkGA1UEBAwyMS1ORVN8Mi1ORVN8My05MmRmZDg2Zi01MGU0LTQzZjQtOTNhNi1iYmU2N2I0MTdkZGMxHzAdBgoJkiaJk/IsZAEBDA8zMTEyNjc5NzEzMDAwMDMxDTALBgNVBAwMBDExMDAxDjAMBgNVBBoMBUpJWkFOMQ8wDQYDVQQPDAZSZXRhaWwwHQYDVR0OBBYEFIELnuwQlXmw19Hll77dhXFSjzzdMB8GA1UdIwQYMBaAFMfA5rep3RLKTz1taIKWIUXzAXWkMIHlBgNVHR8Egd0wgdowgdeggdSggdGGgc5sZGFwOi8vL0NOPVBFWkVJTlZPSUNFU0NBNC1DQSgxKSxDTj1QUlpFSU5WT0lDRVBLSTQsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9ZXh0emF0Y2EsREM9Z292LERDPWxvY2FsP2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludDCBzgYIKwYBBQUHAQEEgcEwgb4wgbsGCCsGAQUFBzAChoGubGRhcDovLy9DTj1QRVpFSU5WT0lDRVNDQTQtQ0EsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9ZXh0emF0Y2EsREM9Z292LERDPWxvY2FsP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MA4GA1UdDwEB/wQEAwIHgDA8BgkrBgEEAYI3FQcELzAtBiUrBgEEAYI3FQiBhqgdhND7EobtnSSHzvsZ08BVZoGc2C2D5cVdAgFkAgEQMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDAzAnBgkrBgEEAYI3FQoEGjAYMAoGCCsGAQUFBwMCMAoGCCsGAQUFBwMDMAoGCCqGSM49BAMCA0cAMEQCIHJDiiSI4A0DUQWRWBCvX9ZHvN7wdgJKNJiB49VJbKM4AiBXsQmAEx+7HTYdXqTHRueDxWtpTBTZEsdLmHvYUtOF7g==";
                    info.PrivateKey = @"MHQCAQEEIFgLdfp5GwjWuvRyKRsqzFVjcmeJIBtlyp4E/dbrcukeoAcGBSuBBAAKoUQDQgAECfK64aDwuNm1eYK0/mbc6K7eXImBnoNpy4VjYs/QQW4N1EBPjLKiEngvlERRbcOCb5QKkL7jr/udrNRnL1170w==";
                    info.SecretKey = @"fBY9hU6zZ4VgHn5sXMXbLhAlPWB+9BjL0ng+/w4MZ4k=";
                }
                
            }
            catch 
            {
                return null;
            }

            return info;
        }

    }
}
